service: data-from-api-to-aws

frameworkVersion: "3"

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - "arn:aws:s3:::melbourne-weather-bucket/*"
  environment:
    TIMEZONE: "Australia/Sydney"

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.py'
#    - '!exclude-me-dir/**'
#    - include-me.py
#    - include-me-dir/**

functions:
  store_api_data:
    handler: handler.store_api_data
    events:
      - eventBridge:
          pattern:
            source:
              - "api_source"
          detail-type:
            - "api_data"
          schedule: rate(3 hours)

# you can add CloudFormation resource templates here
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: melbourne-weather-bucket
